# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCTALib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCTALib
  pod 'CCTALib', path: ".."

end

target 'CCTALibMac' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCTALibMac
  pod 'CCTALib', path: ".."
  
end
